apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicy
metadata:
  name: mutate-bfb-registry-privileged
spec:
  failurePolicy: Fail
  reinvocationPolicy: Never
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["pods"]
  matchConditions:
  - name: is-bfb-registry-pod
    expression: >-
      object.metadata.namespace == "dpf-operator-system" &&
      has(object.metadata.labels) &&
      "dpu.nvidia.com/component" in object.metadata.labels &&
      object.metadata.labels["dpu.nvidia.com/component"] == "bfb-registry"
  mutations:
  - patchType: ApplyConfiguration
    applyConfiguration:
      expression: >-
        Object{
          spec: Object.spec{
            containers: [
              Object.spec.containers{
                name: object.spec.containers[0].name,
                securityContext: Object.spec.containers.securityContext{
                  privileged: true
                }
              }
            ]
          }
        }
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: mutate-bfb-registry-privileged-binding
spec:
  policyName: mutate-bfb-registry-privileged
