apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-nmstate-bridge
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,<BASE64_APPLY_NMSTATE_BRIDGE>
          mode: 0755
          overwrite: true
          path: /usr/local/bin/apply-nmstate-bridge.sh
        - contents:
            source: data:text/plain;charset=utf-8;base64,<BASE64_CONFIGURE_P0_ROUTING>
          mode: 0755
          overwrite: true
          path: /usr/local/bin/configure-p0-routing.sh
        - contents:
            source: data:text/plain;charset=utf-8;base64,<BASE64_UNMANAGE_OVNK_INTERFACE>
          mode: 0644
          overwrite: true
          path: "/etc/NetworkManager/conf.d/unmanage-ovnk-interface.conf"
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Apply NMState bridge configuration
            After=network.target NetworkManager.service nodeip-configuration.service nmstate.service
            
            [Service]
            Type=oneshot
            ExecStart=/usr/local/bin/apply-nmstate-bridge.sh <NODES_MTU>
            RemainAfterExit=yes
            Restart=on-failure
            RestartSec=10
            
            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: nmstate-bridge.service
        - name: ovs-configuration.service
          enabled: false
        - name: openvswitch.service
          enabled: false
          mask: true
        - name: wait-for-br-ex-up.service
          enabled: false
        - name: p0-routing.service
          enabled: true
          contents: |
            [Unit]
            Description=Configure p0 interface routing
            After=kubelet.service network-online.target
            Wants=network-online.target
            
            [Service]
            Type=oneshot
            ExecStart=/usr/local/bin/configure-p0-routing.sh
            RemainAfterExit=yes
            StandardOutput=journal
            StandardError=journal
            Restart=on-failure
            RestartSec=10
            
            [Install]
            WantedBy=multi-user.target
