apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUDeployment
metadata:
  name: dpudeployment
  namespace: dpf-operator-system
spec:
  dpus:
    bfb: bf-bundle
    flavor: flavor
    dpuSets:
    - nameSuffix: "dpuset1"
      dpuAnnotations:
        noderesources.dpu.nvidia.com/nodesriovdevicepluginconfig: bf3-p0-vfs
      nodeSelector:
        matchLabels:
          feature.node.kubernetes.io/dpu-enabled: ""
  services:
    hbn:
      serviceTemplate: hbn
      serviceConfiguration: hbn
    ovn:
      serviceTemplate: ovn
      serviceConfiguration: ovn
    doca-telemetry-service:
      serviceTemplate: doca-telemetry-service
      serviceConfiguration: doca-telemetry-service
  serviceChains:
    switches:
      - ports:
        - serviceInterface:
            matchLabels:
              uplink: p0
        - service:
            name: hbn
            interface: p0_if
      - ports:
        - serviceInterface:
            matchLabels:
              uplink: p1
        - service:
            name: hbn
            interface: p1_if
      - ports:
        - serviceInterface:
            matchLabels:
              port: ovn
        - service:
            name: hbn
            interface: pf2dpu2_if
